# Form implementation generated from reading ui file '.\Main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1118, 729)
        MainWindow.setMinimumSize(QtCore.QSize(1118, 729))
        MainWindow.setMaximumSize(QtCore.QSize(1118, 729))
        MainWindow.setStyleSheet("background-color: rgb(18, 18, 18);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -10, 1111, 751))
        self.stackedWidget.setWhatsThis("")
        self.stackedWidget.setStyleSheet("background-color: rgb(18, 18, 18);\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.pg1_InfoForm = QtWidgets.QFrame(parent=self.page_1)
        self.pg1_InfoForm.setGeometry(QtCore.QRect(20, 220, 401, 451))
        self.pg1_InfoForm.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    background-color: rgb(31, 31, 31);\n"
"    border-radius: 10px;\n"
"}")
        self.pg1_InfoForm.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pg1_InfoForm.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pg1_InfoForm.setObjectName("pg1_InfoForm")
        self.label_20 = QtWidgets.QLabel(parent=self.pg1_InfoForm)
        self.label_20.setGeometry(QtCore.QRect(10, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_20.setObjectName("label_20")
        self.label_29 = QtWidgets.QLabel(parent=self.pg1_InfoForm)
        self.label_29.setGeometry(QtCore.QRect(15, 50, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_29.setObjectName("label_29")
        self.pg1_NameInp = QtWidgets.QLineEdit(parent=self.pg1_InfoForm)
        self.pg1_NameInp.setGeometry(QtCore.QRect(155, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg1_NameInp.setFont(font)
        self.pg1_NameInp.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg1_NameInp.setObjectName("pg1_NameInp")
        self.label_31 = QtWidgets.QLabel(parent=self.pg1_InfoForm)
        self.label_31.setGeometry(QtCore.QRect(15, 105, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_31.setObjectName("label_31")
        self.pg1_RollNoInp = QtWidgets.QLineEdit(parent=self.pg1_InfoForm)
        self.pg1_RollNoInp.setGeometry(QtCore.QRect(155, 100, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg1_RollNoInp.setFont(font)
        self.pg1_RollNoInp.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg1_RollNoInp.setObjectName("pg1_RollNoInp")
        self.pg1_inforBoldCB = QtWidgets.QCheckBox(parent=self.pg1_InfoForm)
        self.pg1_inforBoldCB.setGeometry(QtCore.QRect(160, 230, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg1_inforBoldCB.setFont(font)
        self.pg1_inforBoldCB.setStyleSheet("QCheckBox{\n"
"    color: rgb(234, 234, 234);\n"
"    \n"
"    background-color: rgb(31, 31, 31);\n"
"}")
        self.pg1_inforBoldCB.setObjectName("pg1_inforBoldCB")
        self.label_33 = QtWidgets.QLabel(parent=self.pg1_InfoForm)
        self.label_33.setGeometry(QtCore.QRect(15, 145, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(parent=self.pg1_InfoForm)
        self.label_34.setGeometry(QtCore.QRect(15, 180, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_34.setObjectName("label_34")
        self.pg1_SectionInp = QtWidgets.QLineEdit(parent=self.pg1_InfoForm)
        self.pg1_SectionInp.setGeometry(QtCore.QRect(155, 140, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg1_SectionInp.setFont(font)
        self.pg1_SectionInp.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg1_SectionInp.setObjectName("pg1_SectionInp")
        self.pg1_CourseInp = QtWidgets.QLineEdit(parent=self.pg1_InfoForm)
        self.pg1_CourseInp.setGeometry(QtCore.QRect(155, 180, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg1_CourseInp.setFont(font)
        self.pg1_CourseInp.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg1_CourseInp.setObjectName("pg1_CourseInp")
        self.pg1_SaveInfoButton = QtWidgets.QPushButton(parent=self.pg1_InfoForm)
        self.pg1_SaveInfoButton.setGeometry(QtCore.QRect(130, 350, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pg1_SaveInfoButton.setFont(font)
        self.pg1_SaveInfoButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pg1_SaveInfoButton.setStyleSheet(" QPushButton {\n"
"    \n"
"    background-color: rgb(30, 203, 27);\n"
"    border: 2px  rgb(31, 31, 31);\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    \n"
"    background-color: rgb(10, 186, 1);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    \n"
"    background-color: rgb(0, 255, 128);\n"
"}")
        self.pg1_SaveInfoButton.setObjectName("pg1_SaveInfoButton")
        self.label_35 = QtWidgets.QLabel(parent=self.pg1_InfoForm)
        self.label_35.setGeometry(QtCore.QRect(80, 270, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(parent=self.pg1_InfoForm)
        self.label_36.setGeometry(QtCore.QRect(85, 290, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_36.setObjectName("label_36")
        self.pg1_NewExisFrame = QtWidgets.QFrame(parent=self.page_1)
        self.pg1_NewExisFrame.setGeometry(QtCore.QRect(440, 220, 661, 451))
        self.pg1_NewExisFrame.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    background-color: rgb(31, 31, 31);\n"
"    border-radius: 10px;\n"
"}")
        self.pg1_NewExisFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pg1_NewExisFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pg1_NewExisFrame.setObjectName("pg1_NewExisFrame")
        self.pg1_next_2 = QtWidgets.QPushButton(parent=self.pg1_NewExisFrame)
        self.pg1_next_2.setGeometry(QtCore.QRect(160, 160, 301, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pg1_next_2.setFont(font)
        self.pg1_next_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pg1_next_2.setMouseTracking(False)
        self.pg1_next_2.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}")
        self.pg1_next_2.setObjectName("pg1_next_2")
        self.pg1_next = QtWidgets.QPushButton(parent=self.pg1_NewExisFrame)
        self.pg1_next.setGeometry(QtCore.QRect(160, 40, 301, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pg1_next.setFont(font)
        self.pg1_next.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pg1_next.setMouseTracking(False)
        self.pg1_next.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}")
        self.pg1_next.setObjectName("pg1_next")
        self.pg1_next_3 = QtWidgets.QPushButton(parent=self.pg1_NewExisFrame)
        self.pg1_next_3.setGeometry(QtCore.QRect(160, 280, 301, 101))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pg1_next_3.setFont(font)
        self.pg1_next_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pg1_next_3.setMouseTracking(False)
        self.pg1_next_3.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}")
        self.pg1_next_3.setObjectName("pg1_next_3")
        self.label_37 = QtWidgets.QLabel(parent=self.pg1_NewExisFrame)
        self.label_37.setGeometry(QtCore.QRect(470, 190, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_37.setObjectName("label_37")
        self.pg2_OverallFrame_3 = QtWidgets.QFrame(parent=self.page_1)
        self.pg2_OverallFrame_3.setGeometry(QtCore.QRect(150, 20, 801, 161))
        self.pg2_OverallFrame_3.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    background-color: rgb(31, 31, 31);\n"
"    border-radius: 10px;\n"
"}")
        self.pg2_OverallFrame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pg2_OverallFrame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pg2_OverallFrame_3.setObjectName("pg2_OverallFrame_3")
        self.label_5 = QtWidgets.QLabel(parent=self.pg2_OverallFrame_3)
        self.label_5.setGeometry(QtCore.QRect(90, 30, 831, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(parent=self.page_2)
        self.label_2.setGeometry(QtCore.QRect(400, 10, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pg2_next = QtWidgets.QPushButton(parent=self.page_2)
        self.pg2_next.setGeometry(QtCore.QRect(800, 630, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pg2_next.setFont(font)
        self.pg2_next.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pg2_next.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}")
        self.pg2_next.setObjectName("pg2_next")
        self.pg2_back = QtWidgets.QPushButton(parent=self.page_2)
        self.pg2_back.setGeometry(QtCore.QRect(200, 630, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pg2_back.setFont(font)
        self.pg2_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pg2_back.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}")
        self.pg2_back.setObjectName("pg2_back")
        self.pg2_ModeFrame = QtWidgets.QFrame(parent=self.page_2)
        self.pg2_ModeFrame.setGeometry(QtCore.QRect(30, 260, 221, 201))
        self.pg2_ModeFrame.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    background-color: rgb(31, 31, 31);\n"
"    border-radius: 10px;\n"
"}")
        self.pg2_ModeFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pg2_ModeFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pg2_ModeFrame.setObjectName("pg2_ModeFrame")
        self.label_9 = QtWidgets.QLabel(parent=self.pg2_ModeFrame)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_9.setObjectName("label_9")
        self.pg2_javaRb = QtWidgets.QRadioButton(parent=self.pg2_ModeFrame)
        self.pg2_javaRb.setGeometry(QtCore.QRect(10, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pg2_javaRb.setFont(font)
        self.pg2_javaRb.setStyleSheet("QRadioButton{\n"
"    color: rgb(234, 234, 234);\n"
"    \n"
"    background-color: rgb(31, 31, 31);\n"
"}")
        self.pg2_javaRb.setObjectName("pg2_javaRb")
        self.pg2_cppRb = QtWidgets.QRadioButton(parent=self.pg2_ModeFrame)
        self.pg2_cppRb.setGeometry(QtCore.QRect(10, 100, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pg2_cppRb.setFont(font)
        self.pg2_cppRb.setStyleSheet("QRadioButton{\n"
"    color: rgb(234, 234, 234);\n"
"    \n"
"    background-color: rgb(31, 31, 31);\n"
"}")
        self.pg2_cppRb.setObjectName("pg2_cppRb")
        self.pg2_cRb = QtWidgets.QRadioButton(parent=self.pg2_ModeFrame)
        self.pg2_cRb.setGeometry(QtCore.QRect(10, 130, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pg2_cRb.setFont(font)
        self.pg2_cRb.setStyleSheet("QRadioButton{\n"
"    color: rgb(234, 234, 234);\n"
"    \n"
"    background-color: rgb(31, 31, 31);\n"
"}")
        self.pg2_cRb.setObjectName("pg2_cRb")
        self.pg2_cRb_2 = QtWidgets.QRadioButton(parent=self.pg2_ModeFrame)
        self.pg2_cRb_2.setGeometry(QtCore.QRect(10, 160, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pg2_cRb_2.setFont(font)
        self.pg2_cRb_2.setStyleSheet("QRadioButton{\n"
"    color: rgb(234, 234, 234);\n"
"    \n"
"    background-color: rgb(31, 31, 31);\n"
"}")
        self.pg2_cRb_2.setObjectName("pg2_cRb_2")
        self.pg2_HeadingsFrame = QtWidgets.QFrame(parent=self.page_2)
        self.pg2_HeadingsFrame.setGeometry(QtCore.QRect(300, 260, 771, 201))
        self.pg2_HeadingsFrame.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    background-color: rgb(31, 31, 31);\n"
"    border-radius: 10px;\n"
"}")
        self.pg2_HeadingsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pg2_HeadingsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pg2_HeadingsFrame.setObjectName("pg2_HeadingsFrame")
        self.label_12 = QtWidgets.QLabel(parent=self.pg2_HeadingsFrame)
        self.label_12.setGeometry(QtCore.QRect(10, 0, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.pg2_HeadingsFrame)
        self.label_13.setGeometry(QtCore.QRect(15, 50, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_13.setObjectName("label_13")
        self.pg2_befcodeBox = QtWidgets.QLineEdit(parent=self.pg2_HeadingsFrame)
        self.pg2_befcodeBox.setGeometry(QtCore.QRect(155, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg2_befcodeBox.setFont(font)
        self.pg2_befcodeBox.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg2_befcodeBox.setObjectName("pg2_befcodeBox")
        self.label_14 = QtWidgets.QLabel(parent=self.pg2_HeadingsFrame)
        self.label_14.setGeometry(QtCore.QRect(395, 50, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_14.setObjectName("label_14")
        self.pg2_befoutBox = QtWidgets.QLineEdit(parent=self.pg2_HeadingsFrame)
        self.pg2_befoutBox.setGeometry(QtCore.QRect(550, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg2_befoutBox.setFont(font)
        self.pg2_befoutBox.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg2_befoutBox.setObjectName("pg2_befoutBox")
        self.label_15 = QtWidgets.QLabel(parent=self.pg2_HeadingsFrame)
        self.label_15.setGeometry(QtCore.QRect(15, 105, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_15.setObjectName("label_15")
        self.pg2_befCodeFont = QtWidgets.QLineEdit(parent=self.pg2_HeadingsFrame)
        self.pg2_befCodeFont.setGeometry(QtCore.QRect(155, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg2_befCodeFont.setFont(font)
        self.pg2_befCodeFont.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg2_befCodeFont.setObjectName("pg2_befCodeFont")
        self.pg2_BfBold = QtWidgets.QCheckBox(parent=self.pg2_HeadingsFrame)
        self.pg2_BfBold.setGeometry(QtCore.QRect(160, 150, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg2_BfBold.setFont(font)
        self.pg2_BfBold.setStyleSheet("QCheckBox{\n"
"    color: rgb(234, 234, 234);\n"
"    \n"
"    background-color: rgb(31, 31, 31);\n"
"}")
        self.pg2_BfBold.setObjectName("pg2_BfBold")
        self.pg2_BoBold = QtWidgets.QCheckBox(parent=self.pg2_HeadingsFrame)
        self.pg2_BoBold.setGeometry(QtCore.QRect(555, 150, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg2_BoBold.setFont(font)
        self.pg2_BoBold.setStyleSheet("QCheckBox{\n"
"    color: rgb(234, 234, 234);\n"
"    \n"
"    background-color: rgb(31, 31, 31);\n"
"}")
        self.pg2_BoBold.setObjectName("pg2_BoBold")
        self.label_16 = QtWidgets.QLabel(parent=self.pg2_HeadingsFrame)
        self.label_16.setGeometry(QtCore.QRect(395, 105, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_16.setObjectName("label_16")
        self.pg2_befoutFont = QtWidgets.QLineEdit(parent=self.pg2_HeadingsFrame)
        self.pg2_befoutFont.setGeometry(QtCore.QRect(550, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg2_befoutFont.setFont(font)
        self.pg2_befoutFont.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg2_befoutFont.setObjectName("pg2_befoutFont")
        self.pg2_OverallFrame = QtWidgets.QFrame(parent=self.page_2)
        self.pg2_OverallFrame.setGeometry(QtCore.QRect(30, 480, 1041, 141))
        self.pg2_OverallFrame.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    background-color: rgb(31, 31, 31);\n"
"    border-radius: 10px;\n"
"}")
        self.pg2_OverallFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pg2_OverallFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pg2_OverallFrame.setObjectName("pg2_OverallFrame")
        self.label_22 = QtWidgets.QLabel(parent=self.pg2_OverallFrame)
        self.label_22.setGeometry(QtCore.QRect(10, 0, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.pg2_OverallFrame)
        self.label_23.setGeometry(QtCore.QRect(10, 40, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_23.setObjectName("label_23")
        self.pg2_genFontsty = QtWidgets.QLineEdit(parent=self.pg2_OverallFrame)
        self.pg2_genFontsty.setGeometry(QtCore.QRect(150, 50, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg2_genFontsty.setFont(font)
        self.pg2_genFontsty.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg2_genFontsty.setObjectName("pg2_genFontsty")
        self.label_25 = QtWidgets.QLabel(parent=self.pg2_OverallFrame)
        self.label_25.setGeometry(QtCore.QRect(10, 95, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_25.setObjectName("label_25")
        self.pg2_genFontsize = QtWidgets.QLineEdit(parent=self.pg2_OverallFrame)
        self.pg2_genFontsize.setGeometry(QtCore.QRect(150, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg2_genFontsize.setFont(font)
        self.pg2_genFontsize.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg2_genFontsize.setObjectName("pg2_genFontsize")
        self.label_24 = QtWidgets.QLabel(parent=self.pg2_OverallFrame)
        self.label_24.setGeometry(QtCore.QRect(450, 40, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_24.setObjectName("label_24")
        self.pg2_OverallFrame_2 = QtWidgets.QFrame(parent=self.page_2)
        self.pg2_OverallFrame_2.setGeometry(QtCore.QRect(30, 80, 1041, 161))
        self.pg2_OverallFrame_2.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    background-color: rgb(31, 31, 31);\n"
"    border-radius: 10px;\n"
"}")
        self.pg2_OverallFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pg2_OverallFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pg2_OverallFrame_2.setObjectName("pg2_OverallFrame_2")
        self.label_8 = QtWidgets.QLabel(parent=self.pg2_OverallFrame_2)
        self.label_8.setGeometry(QtCore.QRect(20, 80, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(229, 229, 229);")
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(parent=self.pg2_OverallFrame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_4.setObjectName("label_4")
        self.pg2_footer_box = QtWidgets.QLineEdit(parent=self.pg2_OverallFrame_2)
        self.pg2_footer_box.setGeometry(QtCore.QRect(150, 90, 871, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pg2_footer_box.setFont(font)
        self.pg2_footer_box.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg2_footer_box.setObjectName("pg2_footer_box")
        self.pg2_header_box = QtWidgets.QLineEdit(parent=self.pg2_OverallFrame_2)
        self.pg2_header_box.setGeometry(QtCore.QRect(150, 30, 871, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pg2_header_box.setFont(font)
        self.pg2_header_box.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg2_header_box.setObjectName("pg2_header_box")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pg3_createNext = QtWidgets.QPushButton(parent=self.page_3)
        self.pg3_createNext.setGeometry(QtCore.QRect(800, 630, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pg3_createNext.setFont(font)
        self.pg3_createNext.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pg3_createNext.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}")
        self.pg3_createNext.setObjectName("pg3_createNext")
        self.label_6 = QtWidgets.QLabel(parent=self.page_3)
        self.label_6.setGeometry(QtCore.QRect(400, 10, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.pg3_back = QtWidgets.QPushButton(parent=self.page_3)
        self.pg3_back.setGeometry(QtCore.QRect(200, 630, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pg3_back.setFont(font)
        self.pg3_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pg3_back.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}")
        self.pg3_back.setObjectName("pg3_back")
        self.pg3_OverallFrame = QtWidgets.QFrame(parent=self.page_3)
        self.pg3_OverallFrame.setGeometry(QtCore.QRect(30, 80, 1041, 111))
        self.pg3_OverallFrame.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    background-color: rgb(31, 31, 31);\n"
"    border-radius: 10px;\n"
"}")
        self.pg3_OverallFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pg3_OverallFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pg3_OverallFrame.setObjectName("pg3_OverallFrame")
        self.label_11 = QtWidgets.QLabel(parent=self.pg3_OverallFrame)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_11.setObjectName("label_11")
        self.textEdit = QtWidgets.QTextEdit(parent=self.pg3_OverallFrame)
        self.textEdit.setGeometry(QtCore.QRect(190, 16, 821, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.pg3_InputFrame = QtWidgets.QFrame(parent=self.page_3)
        self.pg3_InputFrame.setGeometry(QtCore.QRect(30, 210, 501, 341))
        self.pg3_InputFrame.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    background-color: rgb(31, 31, 31);\n"
"    border-radius: 10px;\n"
"}")
        self.pg3_InputFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pg3_InputFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pg3_InputFrame.setObjectName("pg3_InputFrame")
        self.label_17 = QtWidgets.QLabel(parent=self.pg3_InputFrame)
        self.label_17.setGeometry(QtCore.QRect(20, 10, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_17.setObjectName("label_17")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.pg3_InputFrame)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 80, 461, 241))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("QTextEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pg3_InputSettingFrame = QtWidgets.QFrame(parent=self.page_3)
        self.pg3_InputSettingFrame.setGeometry(QtCore.QRect(570, 210, 501, 341))
        self.pg3_InputSettingFrame.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    background-color: rgb(31, 31, 31);\n"
"    border-radius: 10px;\n"
"}")
        self.pg3_InputSettingFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pg3_InputSettingFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pg3_InputSettingFrame.setObjectName("pg3_InputSettingFrame")
        self.label_18 = QtWidgets.QLabel(parent=self.pg3_InputSettingFrame)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.pg3_InputSettingFrame)
        self.label_19.setGeometry(QtCore.QRect(20, 80, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_19.setObjectName("label_19")
        self.pg3_IpFrequency = QtWidgets.QLineEdit(parent=self.pg3_InputSettingFrame)
        self.pg3_IpFrequency.setGeometry(QtCore.QRect(170, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg3_IpFrequency.setFont(font)
        self.pg3_IpFrequency.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg3_IpFrequency.setObjectName("pg3_IpFrequency")
        self.label_21 = QtWidgets.QLabel(parent=self.pg3_InputSettingFrame)
        self.label_21.setGeometry(QtCore.QRect(20, 150, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_21.setObjectName("label_21")
        self.pg3_fontsizInp = QtWidgets.QLineEdit(parent=self.pg3_InputSettingFrame)
        self.pg3_fontsizInp.setGeometry(QtCore.QRect(170, 150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg3_fontsizInp.setFont(font)
        self.pg3_fontsizInp.setStyleSheet("QLineEdit{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg3_fontsizInp.setObjectName("pg3_fontsizInp")
        self.pg3_boldIp = QtWidgets.QCheckBox(parent=self.pg3_InputSettingFrame)
        self.pg3_boldIp.setGeometry(QtCore.QRect(180, 200, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg3_boldIp.setFont(font)
        self.pg3_boldIp.setStyleSheet("QCheckBox{\n"
"    color: rgb(234, 234, 234);\n"
"    \n"
"    background-color: rgb(31, 31, 31);\n"
"}")
        self.pg3_boldIp.setObjectName("pg3_boldIp")
        self.label_26 = QtWidgets.QLabel(parent=self.pg3_InputSettingFrame)
        self.label_26.setGeometry(QtCore.QRect(280, 80, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(parent=self.pg3_InputSettingFrame)
        self.label_27.setGeometry(QtCore.QRect(280, 140, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.pg3_InputSettingFrame)
        self.label_28.setGeometry(QtCore.QRect(280, 160, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(234, 234, 234);")
        self.label_28.setObjectName("label_28")
        self.pg3_NextQusButton = QtWidgets.QPushButton(parent=self.pg3_InputSettingFrame)
        self.pg3_NextQusButton.setGeometry(QtCore.QRect(40, 260, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pg3_NextQusButton.setFont(font)
        self.pg3_NextQusButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pg3_NextQusButton.setStyleSheet(" QPushButton {\n"
"    \n"
"    background-color: rgb(30, 203, 27);\n"
"    border: 2px  rgb(31, 31, 31);\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    \n"
"    background-color: rgb(10, 186, 1);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    \n"
"    background-color: rgb(0, 255, 128);\n"
"}")
        self.pg3_NextQusButton.setObjectName("pg3_NextQusButton")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.pg4_back = QtWidgets.QPushButton(parent=self.page_4)
        self.pg4_back.setGeometry(QtCore.QRect(200, 630, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pg4_back.setFont(font)
        self.pg4_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pg4_back.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}")
        self.pg4_back.setObjectName("pg4_back")
        self.pg4_quit = QtWidgets.QPushButton(parent=self.page_4)
        self.pg4_quit.setGeometry(QtCore.QRect(800, 630, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pg4_quit.setFont(font)
        self.pg4_quit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pg4_quit.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(12, 44, 255);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"      \n"
"    background-color: rgb(0, 2, 147);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(75, 192, 255);\n"
"}")
        self.pg4_quit.setObjectName("pg4_quit")
        self.label_7 = QtWidgets.QLabel(parent=self.page_4)
        self.label_7.setGeometry(QtCore.QRect(110, 230, 911, 141))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.label_7.setObjectName("label_7")
        self.pg4_ThankFrame = QtWidgets.QFrame(parent=self.page_4)
        self.pg4_ThankFrame.setGeometry(QtCore.QRect(90, 10, 951, 161))
        self.pg4_ThankFrame.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    background-color: rgb(31, 31, 31);\n"
"    border-radius: 10px;\n"
"}")
        self.pg4_ThankFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pg4_ThankFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pg4_ThankFrame.setObjectName("pg4_ThankFrame")
        self.label_10 = QtWidgets.QLabel(parent=self.pg4_ThankFrame)
        self.label_10.setGeometry(QtCore.QRect(80, 30, 881, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.pg4_TextBrowsr = QtWidgets.QTextBrowser(parent=self.page_4)
        self.pg4_TextBrowsr.setGeometry(QtCore.QRect(110, 400, 911, 192))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pg4_TextBrowsr.setFont(font)
        self.pg4_TextBrowsr.setStyleSheet("QTextBrowser{\n"
"\n"
"    color: rgb(234, 234, 234);\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 2pxs solid rgb(11, 11, 11);\n"
"    border-radius: 12px;\n"
"}")
        self.pg4_TextBrowsr.setOpenExternalLinks(True)
        self.pg4_TextBrowsr.setObjectName("pg4_TextBrowsr")
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_20.setText(_translate("MainWindow", "Information"))
        self.label_29.setText(_translate("MainWindow", "Name"))
        self.label_31.setText(_translate("MainWindow", "Roll no."))
        self.pg1_inforBoldCB.setText(_translate("MainWindow", "Bold"))
        self.label_33.setText(_translate("MainWindow", "Section"))
        self.label_34.setText(_translate("MainWindow", "Course"))
        self.pg1_SaveInfoButton.setText(_translate("MainWindow", "Save"))
        self.label_35.setText(_translate("MainWindow", " This information will be used to insert"))
        self.label_36.setText(_translate("MainWindow", "these details in your practical file only"))
        self.pg1_next_2.setWhatsThis(_translate("MainWindow", "This is jhoncena"))
        self.pg1_next_2.setText(_translate("MainWindow", "Load File"))
        self.pg1_next.setWhatsThis(_translate("MainWindow", "This is jhoncena"))
        self.pg1_next.setText(_translate("MainWindow", "New"))
        self.pg1_next_3.setWhatsThis(_translate("MainWindow", "This is jhoncena"))
        self.pg1_next_3.setText(_translate("MainWindow", "About"))
        self.label_37.setText(_translate("MainWindow", "*In Progress"))
        self.label_5.setText(_translate("MainWindow", "Practical File Formatter"))
        self.label_2.setText(_translate("MainWindow", "Settings Page"))
        self.pg2_next.setText(_translate("MainWindow", "Next"))
        self.pg2_back.setText(_translate("MainWindow", "Back"))
        self.label_9.setText(_translate("MainWindow", "Mode"))
        self.pg2_javaRb.setText(_translate("MainWindow", "Java"))
        self.pg2_cppRb.setText(_translate("MainWindow", "C++"))
        self.pg2_cRb.setText(_translate("MainWindow", "C"))
        self.pg2_cRb_2.setText(_translate("MainWindow", "Python"))
        self.label_12.setText(_translate("MainWindow", "Headings"))
        self.label_13.setText(_translate("MainWindow", "Before Code"))
        self.label_14.setText(_translate("MainWindow", "Before Ouput"))
        self.label_15.setText(_translate("MainWindow", "Font Size"))
        self.pg2_BfBold.setText(_translate("MainWindow", "Bold"))
        self.pg2_BoBold.setText(_translate("MainWindow", "Bold"))
        self.label_16.setText(_translate("MainWindow", "Font Size"))
        self.label_22.setText(_translate("MainWindow", "Overall Font"))
        self.label_23.setText(_translate("MainWindow", "Font"))
        self.label_25.setText(_translate("MainWindow", "Font Size"))
        self.label_24.setText(_translate("MainWindow", "Recommended: Times New Roman"))
        self.label_8.setText(_translate("MainWindow", "Footer"))
        self.label_4.setText(_translate("MainWindow", "Header"))
        self.pg3_createNext.setText(_translate("MainWindow", "Create"))
        self.label_6.setText(_translate("MainWindow", "Input Set Page"))
        self.pg3_back.setText(_translate("MainWindow", "Back"))
        self.label_11.setText(_translate("MainWindow", "Question"))
        self.label_17.setText(_translate("MainWindow", "Input"))
        self.label_18.setText(_translate("MainWindow", "Input Settings"))
        self.label_19.setText(_translate("MainWindow", "Frequency (TestCases)"))
        self.label_21.setText(_translate("MainWindow", "Font Size"))
        self.pg3_boldIp.setText(_translate("MainWindow", "Bold"))
        self.label_26.setText(_translate("MainWindow", "Recommended: 3"))
        self.label_27.setText(_translate("MainWindow", "If left empty: (Overall Font) Setting"))
        self.label_28.setText(_translate("MainWindow", "will be used.(prev page)"))
        self.pg3_NextQusButton.setText(_translate("MainWindow", "Next Question"))
        self.pg4_back.setText(_translate("MainWindow", "Back"))
        self.pg4_quit.setText(_translate("MainWindow", "Quit"))
        self.label_7.setText(_translate("MainWindow", "If you face any issue during execution, kindly report to me via github or linkedin. "))
        self.label_10.setText(_translate("MainWindow", "Thanks For Using My Project"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
